### ISSUE TITLE
13. Roman to Integer 

### ISSUE THREAD

**Issue by khushij12** [piyushsharma220699/Hacktoberfest-2021#136] opened 2021-10-01 20:54 UTC
Can you assigned this to me for C++.

**Comment by anushkarjain** [comment] 2021-10-02 02:20
Please assign this to me in C++

**Comment by piyushsharma220699** [comment] 2021-10-02 04:35
@khushij12 @anushkarjain Sorry :) The issue is already assigned to @Piyush228 here :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/13

Please create an issue for another problem or check the existing issues to get them assigned to you 👍🏻 For now, I'm closing this issue.

**Closed by piyushsharma220699** 2021-10-02 04:35 UTC
