### ISSUE TITLE
31. Next Permutaion [Leetcode - Medium]

### ISSUE THREAD

**Issue by Lekheshwar** [piyushsharma220699/Hacktoberfest-2021#85] opened 2021-10-01 18:18 UTC
Can you please assign this to me.

**Comment by piyushsharma220699** [comment] 2021-10-01 18:23
The issue is already created, please comment there your preferred language to get this assigned to you! 🔢 @Lekheshwar

**Closed by piyushsharma220699** 2021-10-01 18:23 UTC
