### ISSUE TITLE
31. Next Permutation

### ISSUE THREAD

**Issue by Lucifer4255** [piyushsharma220699/Hacktoberfest-2021#142] opened 2021-10-02 04:58 UTC
Please assign me this problem in cpp for hacktoberfest

**Comment by piyushsharma220699** [comment] 2021-10-02 05:08
Please check this :: https://github.com/piyushsharma220699/Hacktoberfest-2021/issues/51
The issue is already assigned to @GuptaTanisha :) Sorry bhai, I'll be closing this issue 👍🏻

**Closed by piyushsharma220699** 2021-10-02 05:08 UTC
